version: '2.0'

services:

  mysql:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=objection_test
      - MYSQL_USER=objection
      - MYSQL_PASSWORD=secret_objection_password
    ports:
      - 3306:3306

  posgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=objection
      - POSTGRES_PASSWORD=secret_objection_password
      - POSTGRES_DB=objection_test
    ports:
      - 5432:5432
